name: Interestelar
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Setup node modules
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
        cache-dependency-path: ./cucumber-with-typescript/package-lock.json

    - run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
    - name: Run Script
      run: npm test ./cucumber-with-typescript
  



