name: First Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Setup node modules
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
        cache-dependency-path: ./package-lock.json
    
    - run: npm ci
    - name: Run Script
      run: npm test