name: PR Runner
on:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  build:
    name: preparing env variables
    runs-on: ubuntu-latest
    env:
      URL_PATH: ${{ secrets.URL_PATH}}
    steps:
      - name: Variables populate
        run: |
          echo "URL_PATH secret variable: $env.URL_PATH"
  test:
    name: test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup node modules
        uses: actions/setup-node@v4
        with:
          node-version: 16.20.2
          cache: npm
      - run: npm ci
      - name: Run Script
        run: npm run test $URL_PATH
