name: Main Runner
on:
  push:
    branches:
      - Main
jobs:
  build:
    name: preparing variables
    runs-on: ubuntu-latest
    environment: Stage
    env:
      URL_NOT_SECRET: ${{ secrets.URL_NOT_SECRET }}
    steps:
      - name: Variables populate
        run: |
          echo "secret variable: $URL_NOT_SECRET"
  test:
    name: test
    runs-on: ubuntu-latest
    environment: Stage
    env:
      URL_NOT_SECRET: ${{ secrets.URL_NOT_SECRET }}
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup node modules
        uses: actions/setup-node@v4
        with:
          node-version: 16.20.2
          cache: npm
      - run: npm ci
      - name: Run Script
        run: npm run test
