name: Tests/Report Runner
on:
  workflow_dispatch:
  push:
    branches:
      - releases/**
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    name: Prep. vars
    runs-on: ubuntu-latest
    environment: Stage
    env:
      URL_NOT_SECRET: ${{ secrets.URL_NOT_SECRET }}
    steps:
      - name: Variables populate
        run: |
          echo "secret variable: $URL_NOT_SECRET"
  test:
    name: test
    runs-on: ubuntu-latest
    environment: Stage
    env:
      URL_NOT_SECRET: ${{ secrets.URL_NOT_SECRET }}
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup node modules
        uses: actions/setup-node@v4
        with:
          node-version: 16.20.2
          cache: npm
      - run: npm ci
      - name: Run Script
        working-directory: ./util
        run: npx ts-node runTest.ts
      - name: Read file and set output variable
        id: read_file
        run: | 
          FILE_CONTENT=$(cat util/cucumber-console-output.txt | base64 | tr -d '\n')
          echo "FILE_CONTENT=${FILE_CONTENT}" >> $GITHUB_ENV
      - name: Decode and use FILE_CONTENT
        run: |
          echo "$FILE_CONTENT" | base64 --decode

  Report:
    name: Send Report
    runs-on: ubuntu-latest
    needs: read_file
    steps:
      - name: Send Report
        run: |
          echo "report sent to slack : $GITHUB_ENV" | base64 --decode

