name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - qa/**
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    name: Prep. vars
    runs-on: ubuntu-latest
    environment: Stage
    env:
      URL_NOT_SECRET: ${{ secrets.URL_NOT_SECRET }}
    steps:
      - name: Variables populate
        run: |
          echo "secret variable: $URL_NOT_SECRET"
  test:
    name: test
    runs-on: ubuntu-latest
    environment: Stage
    env:
      URL: ${{ secrets.URL }}
      CUCUMBER_PUBLISH_TOKEN: ${{ secrets.CUCUMBER_PUBLISH_TOKEN }}
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup node modules
        uses: actions/setup-node@v4
        with:
          node-version: 16.20.2
          cache: npm
      - run: npm ci
      - name: Export cucumber publish variable
        run: |
          export CUCUMBER_PUBLISH_TOKEN=$CUCUMBER_PUBLISH_TOKEN
      - name: Run Script
        run: npm run test:cucumber
      - name: Upload cucumber report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: report.json

  deploy:
    name: Deploy Report to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - name: Download cucumber report artifact
        uses: actions/download-artifact@v3
        with:
          name: cucumber-report

      - name: Move cucumber report to docs folder
        run: |
          mkdir -p docs
          mv report.json docs/

      - name: Commit and push to gh-pages
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Update cucumber report"
          add: "docs/*"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          publish_dir: ./docs
  