name: Run Tests by Tag

on:
  push:
  workflow_dispatch:
    inputs:
      job_to_run:
        description: 'select the test to execute'
        required: true
        type: choice
        options:
          - smoke
          - regression

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      cache-name: cache node modules
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        id: CacheStep
        uses: actions/cache@v2
        with:
          path: node_modules
          key: >-
            ${{ runner.os }}-node-${{ env.cache-name }}-${{
            hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2

      - name: Install with CI
        if: steps.CacheStep.outputs.cache-hit != 'true'
        run: npm ci

  smoke:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job_to_run == 'smoke' }}
    environment: Stage
    env:
      URL: '${{ secrets.URL }}'
      TAG: '@smoke'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        id: CacheStep
        uses: actions/cache@v2
        with:
          path: node_modules
          key: >-
            ${{ runner.os }}-node-${{ env.cache-name }}-${{
            hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2

      - name: Install with CI
        if: steps.CacheStep.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run smoke tests
        run: npm run test:cucumber --tags ${{ env.TAG }}

  regression:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job_to_run == 'regression' }}
    environment: Stage
    env:
      URL: '${{ secrets.URL }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        id: CacheStep
        uses: actions/cache@v2
        with:
          path: node_modules
          key: >-
            ${{ runner.os }}-node-${{ env.cache-name }}-${{
            hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2

      - name: Install with CI
        if: steps.CacheStep.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run regression tests
        run: 'npm run test-tag:regression'
