name: Run Tests by Tag

on:
  push:
    branches:
      - qa/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      cache-name: cache node modules
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        id: CacheStep
        uses: actions/cache@v2
        with:
          path: node_modules
          key: >-
            ${{ runner.os }}-node-${{ env.cache-name }}-${{
            hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2

      - name: Install with CI
        if: steps.CacheStep.outputs.cache-hit != 'true'
        run: npm ci

      - name: where am I
        run: pwd

      - name: what I have
        run: ls -R

      - name: Run smoke tests
        run: 'npm run test-tag:smoke'

  smoke:
    needs: build
    runs-on: ubuntu-latest
    environment: Stage
    env:
      URL: '${{ secrets.URL }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        id: CacheStep
        uses: actions/cache@v2
        with:
          path: node_modules
          key: >-
            ${{ runner.os }}-node-${{ env.cache-name }}-${{
            hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2

      - name: Install with CI
        if: steps.CacheStep.outputs.cache-hit != 'true'
        run: npm ci

      - name: where am I
        run: pwd

      - name: what I have
        run: ls -R

      - name: Run smoke tests
        run: 'npm run test-tag:smoke'

  regression:
    needs: build
    runs-on: ubuntu-latest
    environment: Stage
    env:
      URL: '${{ secrets.URL }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        id: CacheStep
        uses: actions/cache@v2
        with:
          path: node_modules
          key: >-
            ${{ runner.os }}-node-${{ env.cache-name }}-${{
            hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2

      - name: Install with CI
        if: steps.CacheStep.outputs.cache-hit != 'true'
        run: npm ci

      - name: where am I
        run: pwd

      - name: what I have
        run: ls -R

      - name: Run regression tests
        run: 'npm run test-tag:regression'
