on: push
name: Interestelar
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       uses: actions/checkout@v4
       name: Installing dependencies
       uses: actions/setup-node@v4
       with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: subdir/package-lock.json
        run: npm ci
        run: npm test
