name: Run Tests by Tag

on:
  push:
    branches:
      - qa/**  # Puedes modificar las ramas según lo necesites.
  workflow_dispatch:
    inputs:
      run_smoke:
        description: 'Do you want to run Smoke tests?'
        required: false
        default: 'false'
      run_regression:
        description: 'Do you want to run Regression tests?'
        required: false
        default: 'false'

jobs:
  # Job de Build: Este siempre se ejecuta.
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
     
  # Job de Smoke: Este solo se ejecuta manualmente después del build.
  smoke:
    needs: build
    runs-on: ubuntu-latest
    environment: Stage
    env:
      URL: ${{ secrets.URL }}      
    steps:
      - name: Approve
        uses: actions/approval@v2
        with:
          approval-type: 'manual'
          environment: 'Stage'
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2
      - name: Restore npm dependencies from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run smoke tests
        run: npm run test:cucumber --tags '@smoke'

  # Job de Regression: Este solo se ejecuta manualmente después del build.
  regression:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_regression == 'true' || github.event_name == 'push' && github.ref == 'refs/heads/qa/regression' }}
    environment: Stage
    env:
      URL: ${{ secrets.URL }}
    steps:
      - name: Approve
        uses: actions/approval@v2
        with:
          approval-type: 'manual'
          environment: 'Stage'
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2
      - name: Restore npm dependencies from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run regression tests
        run: npm run test:cucumber --tags '@smoke'
