name: Run Tests by Tag

on:
  push:
  workflow_dispatch:
    inputs:
      run_smoke:
        description: ¿Ejecutar pruebas de Smoke?
        required: false
        default: "false"
        type: boolean
      run_regression:
        description: ¿Ejecutar pruebas de Regression?
        required: false
        default: "false"
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Complete Build Process
        run: npm run build

  smoke:
    needs: build
    if: ${{ github.event.inputs.run_smoke == 'true' }}
    runs-on: ubuntu-latest
    environment: Stage
    env:
      URL: ${{ secrets.URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2
      - name: Restore npm dependencies from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run smoke tests
        run: TAGS="@smoke" npm run test-tag:cucumber

  regression:
    needs: build
    if: ${{ github.event.inputs.run_regression == 'true' }}
    runs-on: ubuntu-latest
    environment: Stage
    env:
      URL: ${{ secrets.URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2
      - name: Restore npm dependencies from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run regression tests
        run: TAGS="@regression" npm run test-tag:cucumber