name: Run Tests by Tag

on:
  push:
    branches:
      - qa/**  # Puedes modificar las ramas según lo necesites.
  workflow_dispatch:

jobs:
  # Job de Build: Este siempre se ejecuta.
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}  # Usado si necesitas pasar el tag para el test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci

  # Job de Smoke: Este solo se ejecuta manualmente después del build.
  smoke:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_smoke == 'true' }}
    environment: Stage
    env:
      URL: ${{ secrets.URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2
      - name: Restore npm dependencies from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run smoke tests
        run: TAGS="@smoke" npm run test-tag:cucumber

  # Job de Regression: Este solo se ejecuta manualmente después del build.
  regression:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_regression == 'true' }}
    environment: Stage
    env:
      URL: ${{ secrets.URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2
      - name: Restore npm dependencies from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run regression tests
        run: TAGS="@regression" npm run test-tag:cucumber