name: Run Tests by Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to filter tests by
        required: true
        default: "@smoke"
        type: string
        
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Set output for tag selection
        id: set_tag
        run: echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT

  smoke:
    needs: build
    if: ${{ needs.build.outputs.tag == '@smoke' }}
    runs-on: ubuntu-latest
    environment: Stage
    env:
      URL: ${{ secrets.URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2
      - name: Restore npm dependencies from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run smoke tests
        run: TAGS="@smoke" npm run test-tag:cucumber

  regression:
    needs: build
    if: ${{ needs.build.outputs.tag == '@regression' }}
    runs-on: ubuntu-latest
    environment: Stage
    env:
      URL: ${{ secrets.URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2
      - name: Restore npm dependencies from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run regression tests
        run: TAGS="@regression" npm run test-tag:cucumber
